version: '2'
services:
  api:
    build: ./api
    links:
      - neo4j
    depends_on:
      - neo4j
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - api
    depends_on:
      - api
  worker:
    build: ./worker
    links:
      - neo4j
    depends_on:
      - neo4j
