version: '2'
services:
  api:
    build: ./api
    links:
      - neo4j
    depends_on:
      - neo4j
    ports:
      - "3000:3000"
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - api
    depends_on:
      - api
  worker:
    build: ./worker
    links:
      - neo4j
      - api
    depends_on:
      - neo4j
      - api
