swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  # - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
parameters:
  skipParam:
    name: skip
    in: query
    type: integer
    description: Amount of items to skip in response
    required: false
  limitParam:
    name: limit
    in: query
    type: integer
    description: Amount of items to limit response to
    required: false
  filterParam:
    name: filter
    in: query
    type: string  
    description: Partial match filter
    required: false
  depthParam:
    name: depth
    in: query
    type: integer
    description: How deep to follow relationships
    required: false
paths:
  /domains:
    # binds a127 app logic to a route
    x-swagger-router-controller: domain
    get:
      description: Returns a list of all domains to the requester
      # used as the method name of the controller
      operationId: listDomains
      parameters:
        - $ref: "#/parameters/skipParam"
        - $ref: "#/parameters/limitParam"
        - $ref: "#/parameters/filterParam"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DomainListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /domains/{domain_name}:
    # binds a127 app logic to a route
    x-swagger-router-controller: domain
    get:
      description: Returns a list of all domains to the requester
      # used as the method name of the controller
      operationId: retrieveDomain
      parameters:
        - name: domain_name
          in: path
          type: string
          required: true
        - $ref: "#/parameters/depthParam"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DomainResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DomainListResponse:
    required:
      - domains
    properties:
      domains:
        type: array
        items:
          type: string
  DomainResponse:
    required:
      - nodes
      - links
    properties:
      nodes:
        type: array
        items:
          type: object
      links:
        type: array
        items: 
          type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
